import type { CategoryConfig, BusinessCategory } from '../types'

export const CATEGORIES: CategoryConfig[] = [
  {
    id: 'FOOD_RESTAURANT' as BusinessCategory,
    name: 'Food & Restaurant',
    nameHi: 'खाना और रेस्टोरेंट',
    icon: 'UtensilsCrossed',
    emoji: '🍽️',
    color: '#FC8019',
    bgColor: '#FFF8F0',
    gradient: 'from-orange-500 to-red-500',
    description: 'Order food from restaurants, cafes, bakeries & more',
    descriptionHi: 'रेस्टोरेंट, कैफ़े, बेकरी से खाना ऑर्डर करें',
    uiInspiration: 'Swiggy + Zomato',
    heroImage: '/images/food-hero.jpg',
    subCategories: [
      { id: 'restaurant', name: 'Restaurant / Dhaba', nameHi: 'रेस्टोरेंट / ढाबा', icon: '🍛' },
      { id: 'cafe', name: 'Café / Coffee Shop', nameHi: 'कैफ़े / कॉफ़ी शॉप', icon: '☕' },
      { id: 'cloud_kitchen', name: 'Cloud Kitchen', nameHi: 'क्लाउड किचन', icon: '🏭' },
      { id: 'bakery', name: 'Bakery & Sweet Shop', nameHi: 'बेकरी और मिठाई', icon: '🧁' },
      { id: 'juice_bar', name: 'Juice Bar / Smoothie', nameHi: 'जूस बार / स्मूदी', icon: '🥤' },
      { id: 'tiffin', name: 'Tiffin Service', nameHi: 'टिफिन सर्विस', icon: '🍱' },
      { id: 'catering', name: 'Catering Service', nameHi: 'केटरिंग सर्विस', icon: '🎪' },
      { id: 'ice_cream', name: 'Ice Cream Parlour', nameHi: 'आइसक्रीम पार्लर', icon: '🍦' },
      { id: 'street_food', name: 'Street Food Stall', nameHi: 'स्ट्रीट फ़ूड', icon: '🌮' },
      { id: 'pizza_burger', name: 'Pizza / Burger Shop', nameHi: 'पिज्ज़ा / बर्गर', icon: '🍕' },
      { id: 'biryani', name: 'Biryani House', nameHi: 'बिरयानी हाउस', icon: '🍚' },
      { id: 'mess', name: 'Mess / Canteen', nameHi: 'मेस / कैंटीन', icon: '🏫' },
      { id: 'fruits_vegs', name: 'Fruit & Vegetable Shop', nameHi: 'फल और सब्ज़ी', icon: '🥬' },
      { id: 'dry_fruits', name: 'Dry Fruits Shop', nameHi: 'ड्राई फ्रूट्स', icon: '🥜' },
      { id: 'spice', name: 'Spice Shop', nameHi: 'मसाला दुकान', icon: '🌶️' },
    ],
  },
  {
    id: 'HEALTHCARE' as BusinessCategory,
    name: 'Healthcare',
    nameHi: 'स्वास्थ्य सेवा',
    icon: 'Heart',
    emoji: '🏥',
    color: '#1E4D8C',
    bgColor: '#F0F7FF',
    gradient: 'from-blue-600 to-teal-500',
    description: 'Consult doctors, book tests, order medicines',
    descriptionHi: 'डॉक्टर से सलाह, टेस्ट बुक करें, दवाई ऑर्डर करें',
    uiInspiration: 'Practo + Apollo 247',
    heroImage: '/images/health-hero.jpg',
    subCategories: [
      { id: 'clinic', name: 'Medical Clinic / OPD', nameHi: 'क्लिनिक / OPD', icon: '🏥' },
      { id: 'hospital', name: 'Hospital', nameHi: 'अस्पताल', icon: '🏨' },
      { id: 'dental', name: 'Dental Clinic', nameHi: 'डेंटल क्लिनिक', icon: '🦷' },
      { id: 'eye', name: 'Eye Clinic / Optician', nameHi: 'आई क्लिनिक', icon: '👁️' },
      { id: 'lab', name: 'Pathology / Diagnostic Lab', nameHi: 'पैथोलॉजी लैब', icon: '🔬' },
      { id: 'pharmacy', name: 'Pharmacy / Medical Store', nameHi: 'फार्मेसी', icon: '💊' },
      { id: 'physio', name: 'Physiotherapy Clinic', nameHi: 'फिजियोथेरेपी', icon: '🏋️' },
      { id: 'ayurveda', name: 'Ayurveda / Naturopathy', nameHi: 'आयुर्वेद', icon: '🌿' },
      { id: 'pediatric', name: 'Pediatric Clinic', nameHi: 'बाल रोग', icon: '👶' },
      { id: 'gynecology', name: 'Gynecology Clinic', nameHi: 'स्त्री रोग', icon: '🤰' },
      { id: 'psychiatry', name: 'Psychiatry / Therapy', nameHi: 'मनोचिकित्सा', icon: '🧠' },
      { id: 'dermatology', name: 'Dermatology Clinic', nameHi: 'त्वचा रोग', icon: '🧴' },
      { id: 'orthopedic', name: 'Orthopedic Clinic', nameHi: 'हड्डी रोग', icon: '🦴' },
      { id: 'ent', name: 'ENT Clinic', nameHi: 'कान नाक गला', icon: '👂' },
      { id: 'homeopathy', name: 'Homeopathy Clinic', nameHi: 'होम्योपैथी', icon: '⚗️' },
      { id: 'dietitian', name: 'Dietitian / Nutritionist', nameHi: 'आहार विशेषज्ञ', icon: '🥗' },
      { id: 'blood_bank', name: 'Blood Bank', nameHi: 'ब्लड बैंक', icon: '🩸' },
      { id: 'nursing_home', name: 'Nursing Home', nameHi: 'नर्सिंग होम', icon: '🏠' },
    ],
  },
  {
    id: 'BEAUTY_WELLNESS' as BusinessCategory,
    name: 'Beauty & Wellness',
    nameHi: 'ब्यूटी और वेलनेस',
    icon: 'Sparkles',
    emoji: '💄',
    color: '#C9A96E',
    bgColor: '#FFF8F0',
    gradient: 'from-rose-400 to-amber-500',
    description: 'Salon, spa, makeup, grooming & wellness services',
    descriptionHi: 'सैलून, स्पा, मेकअप, ग्रूमिंग सेवाएं',
    uiInspiration: 'Urban Company + Nykaa',
    heroImage: '/images/beauty-hero.jpg',
    subCategories: [
      { id: 'mens_salon', name: "Men's Salon / Barber", nameHi: 'पुरुष सैलून', icon: '💇‍♂️' },
      { id: 'ladies_parlour', name: 'Ladies Beauty Parlour', nameHi: 'लेडीज़ पार्लर', icon: '💇‍♀️' },
      { id: 'unisex_salon', name: 'Unisex Salon', nameHi: 'यूनिसेक्स सैलून', icon: '✂️' },
      { id: 'spa', name: 'Spa & Wellness Center', nameHi: 'स्पा सेंटर', icon: '🧖' },
      { id: 'nail_studio', name: 'Nail Studio', nameHi: 'नेल स्टूडियो', icon: '💅' },
      { id: 'mehndi', name: 'Mehndi Artist', nameHi: 'मेहंदी आर्टिस्ट', icon: '🎨' },
      { id: 'tattoo', name: 'Tattoo Studio', nameHi: 'टैटू स्टूडियो', icon: '🖌️' },
      { id: 'massage', name: 'Massage Therapy', nameHi: 'मसाज थेरेपी', icon: '💆' },
      { id: 'makeup_artist', name: 'Makeup Artist', nameHi: 'मेकअप आर्टिस्ट', icon: '💄' },
      { id: 'bridal', name: 'Bridal Studio', nameHi: 'ब्राइडल स्टूडियो', icon: '👰' },
      { id: 'skin_care', name: 'Skin Care Clinic', nameHi: 'स्किन केयर', icon: '✨' },
      { id: 'hair_transplant', name: 'Hair Transplant', nameHi: 'हेयर ट्रांसप्लांट', icon: '💇' },
      { id: 'laser', name: 'Laser Studio', nameHi: 'लेज़र स्टूडियो', icon: '⚡' },
      { id: 'slimming', name: 'Slimming / Weight Loss', nameHi: 'वजन घटाना', icon: '📏' },
      { id: 'home_salon', name: 'Home Salon Service', nameHi: 'होम सैलून सर्विस', icon: '🏠' },
    ],
  },
  {
    id: 'EDUCATION' as BusinessCategory,
    name: 'Education',
    nameHi: 'शिक्षा',
    icon: 'GraduationCap',
    emoji: '📚',
    color: '#5B2D8E',
    bgColor: '#F5F0FF',
    gradient: 'from-purple-600 to-indigo-600',
    description: 'Coaching, tutoring, courses, skill development',
    descriptionHi: 'कोचिंग, ट्यूशन, कोर्स, कौशल विकास',
    uiInspiration: "Byju's + Unacademy",
    heroImage: '/images/education-hero.jpg',
    subCategories: [
      { id: 'coaching', name: 'Coaching Institute', nameHi: 'कोचिंग संस्थान', icon: '📖' },
      { id: 'school', name: 'School / Academy', nameHi: 'स्कूल / अकादमी', icon: '🏫' },
      { id: 'dance', name: 'Dance Academy', nameHi: 'डांस अकादमी', icon: '💃' },
      { id: 'music', name: 'Music School', nameHi: 'म्यूजिक स्कूल', icon: '🎵' },
      { id: 'yoga', name: 'Yoga Studio', nameHi: 'योगा स्टूडियो', icon: '🧘' },
      { id: 'coding', name: 'Coding Bootcamp', nameHi: 'कोडिंग बूटकैंप', icon: '💻' },
      { id: 'art', name: 'Art & Drawing Classes', nameHi: 'कला कक्षा', icon: '🎨' },
      { id: 'driving', name: 'Driving School', nameHi: 'ड्राइविंग स्कूल', icon: '🚗' },
      { id: 'cooking', name: 'Cooking Class', nameHi: 'कुकिंग क्लास', icon: '👨‍🍳' },
      { id: 'language', name: 'Spoken English / Language', nameHi: 'भाषा कक्षा', icon: '🗣️' },
      { id: 'nursery', name: 'Nursery / Play School', nameHi: 'प्ले स्कूल', icon: '🧒' },
      { id: 'home_tutor', name: 'Home Tutor', nameHi: 'होम ट्यूटर', icon: '📝' },
      { id: 'library', name: 'Library / Reading Room', nameHi: 'पुस्तकालय', icon: '📚' },
      { id: 'sports_coaching', name: 'Sports Coaching', nameHi: 'स्पोर्ट्स कोचिंग', icon: '⚽' },
    ],
  },
  {
    id: 'FITNESS_SPORTS' as BusinessCategory,
    name: 'Fitness & Sports',
    nameHi: 'फिटनेस और खेल',
    icon: 'Dumbbell',
    emoji: '💪',
    color: '#57FF31',
    bgColor: '#1A1A2E',
    gradient: 'from-green-400 to-emerald-600',
    description: 'Gym, sports facilities, fitness classes & more',
    descriptionHi: 'जिम, खेल सुविधाएं, फिटनेस क्लासेज़',
    uiInspiration: 'Cult.fit + Fittr',
    heroImage: '/images/fitness-hero.jpg',
    subCategories: [
      { id: 'gym', name: 'Gym / Fitness Center', nameHi: 'जिम / फिटनेस सेंटर', icon: '🏋️' },
      { id: 'cricket', name: 'Cricket Academy', nameHi: 'क्रिकेट अकादमी', icon: '🏏' },
      { id: 'football', name: 'Football / Sports Turf', nameHi: 'फुटबॉल टर्फ', icon: '⚽' },
      { id: 'swimming', name: 'Swimming Pool', nameHi: 'स्विमिंग पूल', icon: '🏊' },
      { id: 'martial_arts', name: 'Martial Arts / Karate', nameHi: 'मार्शल आर्ट', icon: '🥋' },
      { id: 'crossfit', name: 'CrossFit', nameHi: 'क्रॉसफिट', icon: '🔥' },
      { id: 'badminton', name: 'Badminton / Tennis Court', nameHi: 'बैडमिंटन / टेनिस', icon: '🏸' },
      { id: 'gymnastics', name: 'Gymnastics Center', nameHi: 'जिम्नास्टिक', icon: '🤸' },
    ],
  },
  {
    id: 'RETAIL_SHOPPING' as BusinessCategory,
    name: 'Retail & Shopping',
    nameHi: 'खरीदारी',
    icon: 'ShoppingCart',
    emoji: '🛒',
    color: '#0077C8',
    bgColor: '#F0F8FF',
    gradient: 'from-blue-500 to-cyan-500',
    description: 'Electronics, clothing, grocery, jewellery & everything',
    descriptionHi: 'इलेक्ट्रॉनिक्स, कपड़े, किराना, ज्वेलरी सब कुछ',
    uiInspiration: 'Amazon + Flipkart + Meesho',
    heroImage: '/images/shopping-hero.jpg',
    subCategories: [
      { id: 'grocery', name: 'Grocery / Kirana Store', nameHi: 'किराना स्टोर', icon: '🛒' },
      { id: 'electronics', name: 'Electronics Shop', nameHi: 'इलेक्ट्रॉनिक्स', icon: '📱' },
      { id: 'clothing', name: 'Clothing / Readymade', nameHi: 'कपड़े की दुकान', icon: '👗' },
      { id: 'boutique', name: 'Boutique / Designer', nameHi: 'बुटीक / डिज़ाइनर', icon: '👘' },
      { id: 'jewellery', name: 'Jewellery Shop', nameHi: 'ज्वेलरी दुकान', icon: '💍' },
      { id: 'furniture', name: 'Furniture Shop', nameHi: 'फर्नीचर', icon: '🛋️' },
      { id: 'mobile', name: 'Mobile & Accessories', nameHi: 'मोबाइल', icon: '📱' },
      { id: 'shoes', name: 'Shoe Shop', nameHi: 'जूते की दुकान', icon: '👟' },
      { id: 'toys', name: 'Toy Store', nameHi: 'खिलौने', icon: '🧸' },
      { id: 'gifts', name: 'Gift Shop', nameHi: 'गिफ्ट शॉप', icon: '🎁' },
      { id: 'hardware', name: 'Hardware Store', nameHi: 'हार्डवेयर', icon: '🔧' },
      { id: 'stationery', name: 'Stationery Shop', nameHi: 'स्टेशनरी', icon: '📝' },
      { id: 'saree', name: 'Saree Shop', nameHi: 'साड़ी', icon: '🥻' },
      { id: 'optician', name: 'Optician / Spectacle', nameHi: 'चश्मा', icon: '👓' },
      { id: 'watch', name: 'Watch Showroom', nameHi: 'घड़ी', icon: '⌚' },
      { id: 'cosmetics', name: 'Cosmetics / Beauty', nameHi: 'कॉस्मेटिक्स', icon: '💄' },
      { id: 'baby', name: 'Baby Care Shop', nameHi: 'बेबी केयर', icon: '🍼' },
      { id: 'pet', name: 'Pet Shop', nameHi: 'पेट शॉप', icon: '🐕' },
      { id: 'florist', name: 'Florist / Flower Shop', nameHi: 'फूल की दुकान', icon: '🌸' },
      { id: 'sports', name: 'Sports Shop', nameHi: 'स्पोर्ट्स शॉप', icon: '🏀' },
    ],
  },
  {
    id: 'HOME_SERVICES' as BusinessCategory,
    name: 'Home Services',
    nameHi: 'घरेलू सेवाएं',
    icon: 'Home',
    emoji: '🏠',
    color: '#2563EB',
    bgColor: '#EFF6FF',
    gradient: 'from-blue-600 to-indigo-600',
    description: 'Electrician, plumber, carpenter, cleaning & repair',
    descriptionHi: 'इलेक्ट्रिशियन, प्लंबर, कारपेंटर, सफाई और मरम्मत',
    uiInspiration: 'Urban Company + NoBroker',
    heroImage: '/images/home-services-hero.jpg',
    subCategories: [
      { id: 'electrician', name: 'Electrician', nameHi: 'इलेक्ट्रिशियन', icon: '⚡' },
      { id: 'plumber', name: 'Plumber', nameHi: 'प्लंबर', icon: '🔧' },
      { id: 'carpenter', name: 'Carpenter', nameHi: 'बढ़ई', icon: '🪚' },
      { id: 'painter', name: 'Painter', nameHi: 'पेंटर', icon: '🖌️' },
      { id: 'ac_repair', name: 'AC Repair & Service', nameHi: 'AC रिपेयर', icon: '❄️' },
      { id: 'ro_service', name: 'RO / Water Purifier', nameHi: 'RO सर्विस', icon: '💧' },
      { id: 'pest_control', name: 'Pest Control', nameHi: 'पेस्ट कंट्रोल', icon: '🐛' },
      { id: 'laundry', name: 'Laundry / Dry Cleaner', nameHi: 'लॉन्ड्री', icon: '👕' },
      { id: 'cleaning', name: 'Home Cleaning', nameHi: 'घर की सफाई', icon: '🧹' },
      { id: 'appliance', name: 'Appliance Repair', nameHi: 'उपकरण मरम्मत', icon: '🔌' },
      { id: 'cctv', name: 'CCTV Installation', nameHi: 'CCTV', icon: '📹' },
      { id: 'locksmith', name: 'Locksmith', nameHi: 'ताला बनाने वाला', icon: '🔐' },
      { id: 'waterproofing', name: 'Waterproofing', nameHi: 'वाटरप्रूफिंग', icon: '🌧️' },
      { id: 'solar', name: 'Solar Panel Installation', nameHi: 'सोलर पैनल', icon: '☀️' },
    ],
  },
  {
    id: 'TRANSPORT_AUTO' as BusinessCategory,
    name: 'Transport & Auto',
    nameHi: 'परिवहन और ऑटो',
    icon: 'Car',
    emoji: '🚗',
    color: '#059669',
    bgColor: '#F0FDF4',
    gradient: 'from-emerald-500 to-green-600',
    description: 'Cab, delivery, garage, rental, packers & movers',
    descriptionHi: 'कैब, डिलीवरी, गैरेज, रेंटल, पैकर्स एंड मूवर्स',
    uiInspiration: 'Ola + Rapido + Porter',
    heroImage: '/images/transport-hero.jpg',
    subCategories: [
      { id: 'cab', name: 'Cab / Taxi Service', nameHi: 'कैब / टैक्सी', icon: '🚕' },
      { id: 'auto', name: 'Auto Rickshaw', nameHi: 'ऑटो रिक्शा', icon: '🛺' },
      { id: 'courier', name: 'Courier / Delivery', nameHi: 'कूरियर / डिलीवरी', icon: '📦' },
      { id: 'garage', name: 'Car Garage / Workshop', nameHi: 'गैरेज', icon: '🔧' },
      { id: 'bike_workshop', name: 'Bike / Scooter Workshop', nameHi: 'बाइक वर्कशॉप', icon: '🏍️' },
      { id: 'car_rental', name: 'Car Rental', nameHi: 'कार किराया', icon: '🚗' },
      { id: 'bike_rental', name: 'Bike Rental', nameHi: 'बाइक किराया', icon: '🚲' },
      { id: 'tyre', name: 'Tyre Shop', nameHi: 'टायर शॉप', icon: '⭕' },
      { id: 'car_wash', name: 'Car Wash', nameHi: 'कार वॉश', icon: '🧽' },
      { id: 'packers', name: 'Packers & Movers', nameHi: 'पैकर्स एंड मूवर्स', icon: '📦' },
      { id: 'truck', name: 'Truck / Tempo Transport', nameHi: 'ट्रक / टेम्पो', icon: '🚛' },
      { id: 'school_van', name: 'School Van Service', nameHi: 'स्कूल वैन', icon: '🚐' },
    ],
  },
  {
    id: 'REAL_ESTATE' as BusinessCategory,
    name: 'Real Estate & Construction',
    nameHi: 'रियल एस्टेट और निर्माण',
    icon: 'Building',
    emoji: '🏢',
    color: '#DC2626',
    bgColor: '#FEF2F2',
    gradient: 'from-red-500 to-rose-600',
    description: 'Property, construction, interior design, PG/hostel',
    descriptionHi: 'प्रॉपर्टी, निर्माण, इंटीरियर डिज़ाइन, PG/होस्टल',
    uiInspiration: '99acres + MagicBricks',
    heroImage: '/images/realestate-hero.jpg',
    subCategories: [
      { id: 'agency', name: 'Real Estate Agency', nameHi: 'रियल एस्टेट एजेंसी', icon: '🏠' },
      { id: 'broker', name: 'Property Dealer / Broker', nameHi: 'प्रॉपर्टी डीलर', icon: '🔑' },
      { id: 'contractor', name: 'Civil Contractor', nameHi: 'सिविल ठेकेदार', icon: '🏗️' },
      { id: 'interior', name: 'Interior Designer', nameHi: 'इंटीरियर डिज़ाइनर', icon: '🎨' },
      { id: 'architect', name: 'Architect Firm', nameHi: 'आर्किटेक्ट', icon: '📐' },
      { id: 'pg', name: 'PG / Hostel', nameHi: 'PG / हॉस्टल', icon: '🏨' },
      { id: 'tiles', name: 'Tiles & Marbles', nameHi: 'टाइल्स और मार्बल', icon: '🪨' },
      { id: 'steel', name: 'Steel / TMT Dealer', nameHi: 'स्टील / TMT', icon: '🔩' },
      { id: 'cement', name: 'Cement Dealer', nameHi: 'सीमेंट', icon: '🧱' },
      { id: 'plywood', name: 'Plywood / Hardware', nameHi: 'प्लाईवुड', icon: '🪵' },
    ],
  },
  {
    id: 'TECHNOLOGY_IT' as BusinessCategory,
    name: 'Technology & IT',
    nameHi: 'तकनीक और IT',
    icon: 'Monitor',
    emoji: '💻',
    color: '#7C3AED',
    bgColor: '#F5F3FF',
    gradient: 'from-violet-600 to-purple-600',
    description: 'Software, web design, mobile repair, IT services',
    descriptionHi: 'सॉफ्टवेयर, वेब डिज़ाइन, मोबाइल रिपेयर, IT सेवाएं',
    uiInspiration: 'Upwork + Fiverr',
    heroImage: '/images/tech-hero.jpg',
    subCategories: [
      { id: 'software', name: 'Software Development', nameHi: 'सॉफ्टवेयर डेवलपमेंट', icon: '💻' },
      { id: 'web_design', name: 'Web Design / UI-UX', nameHi: 'वेब डिज़ाइन', icon: '🎨' },
      { id: 'it_support', name: 'IT Support', nameHi: 'IT सपोर्ट', icon: '🖥️' },
      { id: 'cyber_cafe', name: 'Cyber Café', nameHi: 'साइबर कैफ़े', icon: '☕' },
      { id: 'mobile_repair', name: 'Mobile Repair', nameHi: 'मोबाइल रिपेयर', icon: '📱' },
      { id: 'cctv_security', name: 'CCTV / Security', nameHi: 'CCTV / सिक्योरिटी', icon: '📹' },
      { id: 'data_recovery', name: 'Data Recovery', nameHi: 'डेटा रिकवरी', icon: '💾' },
      { id: 'digital_marketing', name: 'Digital Marketing', nameHi: 'डिजिटल मार्केटिंग', icon: '📊' },
    ],
  },
  {
    id: 'FINANCE_LEGAL' as BusinessCategory,
    name: 'Finance & Legal',
    nameHi: 'वित्त और कानूनी',
    icon: 'Landmark',
    emoji: '📊',
    color: '#0369A1',
    bgColor: '#F0F9FF',
    gradient: 'from-sky-600 to-blue-700',
    description: 'CA, loans, insurance, legal services',
    descriptionHi: 'CA, लोन, बीमा, कानूनी सेवाएं',
    uiInspiration: 'ClearTax + LegalKart',
    heroImage: '/images/finance-hero.jpg',
    subCategories: [
      { id: 'ca', name: 'CA / Accounting', nameHi: 'CA / लेखा', icon: '📊' },
      { id: 'tax', name: 'Tax Consultant / GST', nameHi: 'टैक्स / GST', icon: '🧾' },
      { id: 'loan', name: 'Loan Agent / DSA', nameHi: 'लोन एजेंट', icon: '💰' },
      { id: 'insurance', name: 'Insurance Agency', nameHi: 'बीमा एजेंसी', icon: '🛡️' },
      { id: 'stock', name: 'Stock Broker / MF', nameHi: 'स्टॉक ब्रोकर', icon: '📈' },
      { id: 'lawyer', name: 'Lawyer / Law Firm', nameHi: 'वकील / लॉ फर्म', icon: '⚖️' },
      { id: 'notary', name: 'Notary / Document', nameHi: 'नोटरी', icon: '📜' },
      { id: 'cs', name: 'Company Secretary', nameHi: 'कंपनी सेक्रेटरी', icon: '🏢' },
      { id: 'immigration', name: 'Immigration Consultant', nameHi: 'इमिग्रेशन', icon: '✈️' },
    ],
  },
  {
    id: 'AGRICULTURE' as BusinessCategory,
    name: 'Agriculture & Farming',
    nameHi: 'कृषि और खेती',
    icon: 'Wheat',
    emoji: '🌾',
    color: '#16A34A',
    bgColor: '#F0FDF4',
    gradient: 'from-green-500 to-lime-500',
    description: 'Seeds, equipment, mandi prices, advisory',
    descriptionHi: 'बीज, उपकरण, मंडी भाव, सलाह',
    uiInspiration: 'AgriBazaar + DeHaat',
    heroImage: '/images/agriculture-hero.jpg',
    subCategories: [
      { id: 'kisan_store', name: 'Agriculture / Kisan Store', nameHi: 'किसान स्टोर', icon: '🌾' },
      { id: 'dairy', name: 'Dairy Farm', nameHi: 'डेयरी फार्म', icon: '🐄' },
      { id: 'poultry', name: 'Poultry Farm', nameHi: 'पोल्ट्री फार्म', icon: '🐔' },
      { id: 'fish', name: 'Fish Farm / Market', nameHi: 'मछली', icon: '🐟' },
      { id: 'nursery', name: 'Plant Nursery', nameHi: 'पौधा नर्सरी', icon: '🌱' },
      { id: 'honey', name: 'Honey Farm', nameHi: 'शहद फार्म', icon: '🍯' },
      { id: 'rice_mill', name: 'Rice Mill / Flour Mill', nameHi: 'चावल / आटा चक्की', icon: '🌾' },
      { id: 'seed', name: 'Seed Store', nameHi: 'बीज दुकान', icon: '🌰' },
      { id: 'animal_feed', name: 'Animal Feed Store', nameHi: 'पशु आहार', icon: '🐾' },
    ],
  },
  {
    id: 'HOSPITALITY_EVENTS' as BusinessCategory,
    name: 'Hospitality & Events',
    nameHi: 'आतिथ्य और इवेंट',
    icon: 'Hotel',
    emoji: '🏨',
    color: '#E11D48',
    bgColor: '#FFF1F2',
    gradient: 'from-rose-500 to-pink-600',
    description: 'Hotels, events, wedding planning, photography',
    descriptionHi: 'होटल, इवेंट, शादी, फोटोग्राफी',
    uiInspiration: 'OYO + BookMyShow + WedMeGood',
    heroImage: '/images/hospitality-hero.jpg',
    subCategories: [
      { id: 'hotel', name: 'Hotel / Lodge', nameHi: 'होटल / लॉज', icon: '🏨' },
      { id: 'guest_house', name: 'Guest House / Homestay', nameHi: 'गेस्ट हाउस', icon: '🏡' },
      { id: 'event_mgmt', name: 'Event Management', nameHi: 'इवेंट मैनेजमेंट', icon: '🎪' },
      { id: 'wedding', name: 'Wedding Planner', nameHi: 'शादी प्लानर', icon: '💒' },
      { id: 'banquet', name: 'Banquet / Function Hall', nameHi: 'बैंक्वेट हॉल', icon: '🏛️' },
      { id: 'tent_house', name: 'Tent House / Decorator', nameHi: 'टेंट हाउस', icon: '🎪' },
      { id: 'travel', name: 'Travel Agency', nameHi: 'ट्रैवल एजेंसी', icon: '✈️' },
      { id: 'resort', name: 'Resort / Retreat', nameHi: 'रिसॉर्ट', icon: '🏖️' },
      { id: 'dj', name: 'DJ Service', nameHi: 'DJ सर्विस', icon: '🎧' },
      { id: 'photography', name: 'Photography Studio', nameHi: 'फोटोग्राफी', icon: '📸' },
      { id: 'videography', name: 'Videography Studio', nameHi: 'वीडियोग्राफी', icon: '🎬' },
    ],
  },
  {
    id: 'MANUFACTURING_B2B' as BusinessCategory,
    name: 'Manufacturing & Wholesale',
    nameHi: 'निर्माण और थोक',
    icon: 'Factory',
    emoji: '⚙️',
    color: '#B45309',
    bgColor: '#FFFBEB',
    gradient: 'from-amber-600 to-orange-700',
    description: 'B2B marketplace, suppliers, manufacturers',
    descriptionHi: 'B2B बाज़ार, सप्लायर्स, मैन्युफैक्चरर',
    uiInspiration: 'IndiaMart + TradeIndia',
    heroImage: '/images/manufacturing-hero.jpg',
    subCategories: [
      { id: 'fabrication', name: 'Steel Fabrication', nameHi: 'स्टील फैब्रिकेशन', icon: '⚙️' },
      { id: 'printing', name: 'Printing Press', nameHi: 'प्रिंटिंग प्रेस', icon: '🖨️' },
      { id: 'packaging', name: 'Packaging Supplier', nameHi: 'पैकेजिंग', icon: '📦' },
      { id: 'textile', name: 'Textile / Weaving', nameHi: 'कपड़ा / बुनाई', icon: '🧵' },
      { id: 'plastic', name: 'Plastic Products', nameHi: 'प्लास्टिक उत्पाद', icon: '♻️' },
      { id: 'food_processing', name: 'Food Processing', nameHi: 'खाद्य प्रसंस्करण', icon: '🏭' },
      { id: 'garment', name: 'Garment Manufacturer', nameHi: 'कपड़ा निर्माता', icon: '👔' },
    ],
  },
  {
    id: 'DIGITAL_ONLINE' as BusinessCategory,
    name: 'Digital / Online Business',
    nameHi: 'डिजिटल / ऑनलाइन बिज़नेस',
    icon: 'Globe',
    emoji: '📱',
    color: '#6D28D9',
    bgColor: '#FAF5FF',
    gradient: 'from-purple-600 to-violet-700',
    description: 'E-commerce, D2C, creators, digital services',
    descriptionHi: 'ई-कॉमर्स, D2C, क्रिएटर्स, डिजिटल सेवाएं',
    uiInspiration: 'Shopify + Linktree',
    heroImage: '/images/digital-hero.jpg',
    subCategories: [
      { id: 'ecommerce', name: 'E-Commerce Store', nameHi: 'ई-कॉमर्स', icon: '🛍️' },
      { id: 'd2c', name: 'D2C Brand', nameHi: 'D2C ब्रांड', icon: '🏷️' },
      { id: 'dropshipping', name: 'Dropshipping Store', nameHi: 'ड्रॉपशिपिंग', icon: '📦' },
      { id: 'news', name: 'News Portal / Blog', nameHi: 'न्यूज़ / ब्लॉग', icon: '📰' },
      { id: 'subscription', name: 'Subscription Box', nameHi: 'सब्सक्रिप्शन बॉक्स', icon: '📬' },
      { id: 'online_coaching', name: 'Online Coaching', nameHi: 'ऑनलाइन कोचिंग', icon: '🎓' },
      { id: 'freelance', name: 'Freelance Agency', nameHi: 'फ्रीलांस एजेंसी', icon: '💼' },
      { id: 'influencer', name: 'Influencer / Creator', nameHi: 'इन्फ्लुएंसर', icon: '⭐' },
    ],
  },
]

export function getCategoryById(id: BusinessCategory): CategoryConfig | undefined {
  return CATEGORIES.find((cat) => cat.id === id)
}

export function getCategoryColor(id: BusinessCategory): string {
  return getCategoryById(id)?.color || '#FC8019'
}

export function getCategoryGradient(id: BusinessCategory): string {
  return getCategoryById(id)?.gradient || 'from-orange-500 to-red-500'
}
